# Algoritmo de Warshall


**Nombre:** Heriberto Espino Montelongo

**Materia:** Análisis Discreto

**Clave:** O24-LDS1011-1

**Fecha:** 4 de diciembre de 2024

#### Contenido de la actividad

Realice el código para implementar el Algoritmo Marshall (usando el seudocódigo visto en clase). Puede probar el código con la gráfica obtenida en la actividad "Gráfica asociada a datos".

```pascal
procedure Warshall {V ∈ {v1, v2, ..., vn}, R ∈ E ⊆ V × V}
begin
    M := adjMatrix(R)  {La matriz (booleana) de adyacencias de R}
    C := M             {Copia M a C}
    CP := C            {Se copia C a CP}
    
    iteracion := 1
    cambio := true     {Registra si hubo cambio}

    while iteracion ≤ n and cambio = true do
        cambio := false
        for i := 1 to n do
            for j := 1 to n do
                for k := 1 to n do
                    CP[i][j] := CP[i][j] or (C[i][k] and M[k][j])
                    cambio := cambio or (C[i][j] ≠ CP[i][j])
        C := CP
        iteracion := iteracion + 1
end


In [1]:
import numpy as np

In [2]:
def warshall(V, R):
    # Number of vertices
    n = len(V)
    
    # Initialize adjacency matrix M
    M = np.zeros((n, n), dtype=bool)
    for (i, j) in R:
        M[i-1][j-1] = True
    
    # Copy M to C
    C = M.copy()
    CP = C.copy()
    
    iteracion = 1
    cambio = True
    
    while iteracion <= n and cambio:
        cambio = False
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    CP[i][j] = CP[i][j] or (C[i][k] and M[k][j])
                    cambio = cambio or (C[i][j] != CP[i][j])
        C = CP.copy()
        iteracion += 1

    C = C.astype(int)

    return C

In [5]:
V = [1, 2, 3, 4, 5, 6, 7, 8]
R = [(1, 2), (1, 3), (2, 4), (4, 2), (4, 3), (4, 5), (4, 6), (5, 3), (5, 4), (5, 7), (6, 4), (6, 7), (6, 8), (7, 5), (7, 6), (7, 8), (8, 6), (8, 7)]
transitive_closure = warshall(V, R)
print(transitive_closure)


[[0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]]
